"""Check COMMIT_MSG.txt against hve-core commit-message.instructions.md.

Rules checked: conventional type(scope)?: description on line 1 (< 100 bytes, imperative is not
machine-checked), optional body of at most 5 bullets after a blank line and under 300 bytes, and a
footer separated by a blank line that carries an emoji and ends with '- Generated by Copilot'.
"""

import re
import sys
import unicodedata
from pathlib import Path

TYPES = "feat|fix|refactor|perf|style|test|docs|build|ops|chore"
HEADER = re.compile(rf"^({TYPES})(\([a-z0-9._/-]+\))?!?: \S.*$")


EMOJI = re.compile("[\U0001F000-\U0001FAFF\u2600-\u27BF\u2B00-\u2BFF]")


def has_emoji(text: str) -> bool:
    """An emoji proper: a Symbol-Other code point from the symbol blocks (U+2600 up) or one in the emoji
    blocks; dashes, ellipses and box-drawing characters do not count."""
    return any((unicodedata.category(ch) == "So" and ord(ch) >= 0x2600) or EMOJI.match(ch) for ch in text)


def main() -> int:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "COMMIT_MSG.txt")
    if not path.exists():
        print(f"FAIL: {path} missing")
        return 1
    text = path.read_text(encoding="utf-8").strip("\n")
    lines = text.split("\n")
    problems = []
    if not HEADER.match(lines[0]):
        problems.append(f"header does not match conventional commit format: {lines[0]!r}")
    if len(lines[0].encode("utf-8")) >= 100:
        problems.append("header must be under 100 bytes")
    footer = lines[-1].strip()
    if not footer.endswith("- Generated by Copilot"):
        problems.append("footer must end with '- Generated by Copilot'")
    if not has_emoji(footer):
        problems.append("footer must include an emoji")
    if len(lines) < 3 or lines[-2].strip() != "":
        problems.append("footer must be preceded by a blank line")
    body = [l for l in lines[1:-2] if l.strip()]
    if body:
        if lines[1].strip() != "":
            problems.append("body must start after a blank line")
        bullets = [l for l in body if l.lstrip().startswith(("-", "*"))]
        if len(bullets) > 5:
            problems.append("body has more than 5 bullets")
        if len("\n".join(body).encode("utf-8")) >= 300:
            problems.append("body must be under 300 bytes")
    for p in problems:
        print("FAIL:", p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
