using System.Runtime.CompilerServices;
using InspectAzureAI.Eval.Agents.Bridge;
using Microsoft.Extensions.AI;
using MafChatMessage = Microsoft.Extensions.AI.ChatMessage;

namespace InspectAzureAI.Maf;

/// <summary>
/// An <see cref="IChatClient"/> over an Inspect <see cref="AgentBridge"/>: every request an Agent Framework agent
/// (or any Microsoft.Extensions.AI consumer) makes is generated by the bridged Inspect model, so transcript events,
/// limits, approval, caching and cost accounting all apply, and the bridge keeps its <see cref="AgentBridge.State"/>
/// in step with the conversation. This is the in-process counterpart of Python's <c>agent_bridge()</c>: no HTTP,
/// no sandbox. Streaming is synthesised from the finished response, as the sandbox bridge does.
/// </summary>
public sealed class InspectChatClient : IChatClient
{
    private readonly ChatClientMetadata _metadata;

    public InspectChatClient(AgentBridge bridge)
    {
        ArgumentNullException.ThrowIfNull(bridge);
        Bridge = bridge;
        _metadata = new ChatClientMetadata("inspect", null, bridge.Model.Name);
    }

    public AgentBridge Bridge { get; }

    public async Task<ChatResponse> GetResponseAsync(IEnumerable<MafChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(messages);
        var input = MafConversion.ToInspectMessages(messages, options?.Instructions);
        var tools = MafConversion.ToToolInfos(options?.Tools);
        var output = await Bridge.GenerateAsync(
            options?.ModelId ?? MafConversion.DefaultModelName,
            input,
            tools,
            MafConversion.ToToolChoice(options?.ToolMode),
            MafConversion.ToGenerateConfig(options),
            cancellationToken).ConfigureAwait(false);
        return MafConversion.ToChatResponse(output);
    }

    public async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<MafChatMessage> messages,
        ChatOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var response = await GetResponseAsync(messages, options, cancellationToken).ConfigureAwait(false);
        foreach (var update in response.ToChatResponseUpdates())
        {
            yield return update;
        }
    }

    public object? GetService(Type serviceType, object? serviceKey = null)
    {
        ArgumentNullException.ThrowIfNull(serviceType);
        if (serviceKey is not null)
        {
            return null;
        }

        if (serviceType == typeof(ChatClientMetadata))
        {
            return _metadata;
        }

        if (serviceType == typeof(AgentBridge))
        {
            return Bridge;
        }

        return serviceType.IsInstanceOfType(this) ? this : null;
    }

    public void Dispose()
    {
    }
}
